default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: agrisurya

test:
  <<: *default
  database: agrisurya_test
  
production:
  <<: *default
  database: agrisurya_prod
